# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI on pull-requests; unit testing and linting

on: [pull_request]

jobs:
  main:
    runs-on: self-hosted
    container: node:16
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run unit tests and linter
        run: |
              npm run test:unit
              npm run lint
